### ISSUE TITLE
Default Theme Mode

### ISSUE THREAD

**Issue by zoop93** [originecode/aemi#3]
Is there anyway i can have the dark mode as the default? My site is designed around it and it looks a lot better with the black header, etc

**Comment by originecode** [comment]
Hello

This feature is in the pipe. Stay tuned.

Best regards

**Comment by originecode** [comment]
> Is there anyway i can have the dark mode as the default? My site is designed around it and it looks a lot better with the black header, etc

Features added in version 2.0-beta4.

Closing this issue.

Best Regards
