### ISSUE TITLE
Mobile Header

### ISSUE THREAD

**Issue by zoop93** [originecode/aemi#4]
Is it possible to have the header stay on the top on mobile?

**Comment by originecode** [comment]
Hello,

Placing the header at the bottom on the mobile is a design choice. However I will take your preference into consideration and perhaps give you the option to put it on top.

Best Regards

**Comment by originecode** [comment]
Hi @zoop93 

I'm glad to announce that Aemi Version 2.0-beta10 is bringing some header settings including fixed-to-top header.

Best Regards
